"""
Clip_Transcriber_Module / clip_transcriber.py
===============================================
AMTCE Standalone Audio Extraction + Faster-Whisper + Gemini Audio-Text Fusion Engine.

Pipeline Flow:
  1. Extract mono 16kHz WAV audio using Audio_Modules.audio_extractor.
  2. Transcribe audio with Faster-Whisper using Audio_Modules.speech_boundary_detector.
  3. Upload WAV audio + pass Faster-Whisper transcript to Gemini Multimodal AI.
  4. Cross-reference audio audio stream with text transcript to fix Whisper errors/omissions.
  5. Output structured JSON + Text summary ready to feed downstream LLMs.
"""

import os
import sys
import json
import time
import logging
from typing import Dict, Any, Optional

logger = logging.getLogger("AMTCE.ClipTranscriber")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")

# Ensure repository paths are accessible
_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(_MODULE_DIR)
_SIMPLER_UPDATE = os.path.join(_REPO_ROOT, "simpler update")

for p in [_REPO_ROOT, _SIMPLER_UPDATE]:
    if os.path.exists(p) and p not in sys.path:
        sys.path.insert(0, p)

# Load environment variables
from dotenv import load_dotenv
if os.path.exists(os.path.join(_REPO_ROOT, ".env")):
    load_dotenv(os.path.join(_REPO_ROOT, ".env"), override=True)
elif os.path.exists(os.path.join(_REPO_ROOT, "Credentials", ".env")):
    load_dotenv(os.path.join(_REPO_ROOT, "Credentials", ".env"), override=True)

# Import AMTCE Root Audio & Gemini Modules
try:
    from Audio_Modules.audio_extractor import extract_audio
    from Audio_Modules.speech_boundary_detector import extract_speech_boundaries
except ImportError:
    try:
        from simpler_update.Audio_Modules.audio_extractor import extract_audio
        from simpler_update.Audio_Modules.speech_boundary_detector import extract_speech_boundaries
    except ImportError as err:
        logger.error(f"❌ Failed to import AMTCE Audio_Modules: {err}")
        raise

try:
    from Gemini_Modules.gemini_router_module.gemini_governor import gemini_router
except ImportError:
    gemini_router = None


GEMINI_CROSS_REF_PROMPT = """
You are an expert Audio-Visual Intelligence Analyst & Forensic Transcriber for AMTCE.
You are provided with:
1. The RAW AUDIO FILE extracted directly from a video clip.
2. A raw transcript generated by Faster-Whisper (including sentence breakdowns and word timestamps).

YOUR MANDATE:
- Listen carefully to the attached WAV audio file while cross-referencing the provided Faster-Whisper text.
- Faster-Whisper is fast but often makes phonetic errors, drops words, mishears technical/brand terms, or misinterprets speech stutters.
- Correct any errors or omissions made by Faster-Whisper based on the actual audio.
- Predict and fill in missing implicit context ("connect every dot") so any downstream LLM reading your output will fully understand literally what is inside the clip.

---
RAW FASTER-WHISPER TRANSCRIPT & SENTENCES:
{whisper_raw_json}
---

Return your response in STRICT, VALID JSON with NO markdown codeblock backticks or extra text outside the JSON object:
{{
  "accurate_full_transcript": "Full, polished, dot-connected dialogue transcript corrected by listening to raw audio.",
  "whisper_corrections": [
    {{
      "whisper_said": "word or phrase from whisper",
      "gemini_corrected": "actual word or phrase heard in audio",
      "reason": "explanation of correction"
    }}
  ],
  "semantic_context": {{
    "topic": "Main topic or category of the video",
    "detailed_narrative": "Detailed, comprehensive explanation of what is literally inside the clip.",
    "speaker_intent": "What the speaker is trying to communicate or accomplish",
    "emotional_tone": "e.g. enthusiastic, instructional, urgent, relaxed, serious",
    "implied_context": "Unspoken background knowledge, context, or implied information"
  }},
  "key_entities_and_facts": {{
    "entities_mentioned": ["list of people, brands, products, software, or locations mentioned"],
    "key_takeaways": ["bullet point takeaways of key information"]
  }},
  "llm_system_context_payload": "A clean, rich, ready-to-use prompt context block formatted for downstream LLMs explaining exactly what happens and is spoken in this clip."
}}
"""


class ClipTranscriber:
    """
    Standalone Clip Transcriber module integrating Faster-Whisper audio transcription
    and Gemini Multimodal Audio-Text Cross-Referencing.
    """

    def __init__(self, whisper_model_size: str = "base"):
        self.whisper_model_size = whisper_model_size
        self.api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")

    def process_clip(
        self,
        video_path: str,
        output_dir: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Executes the full pipeline:
          1. Extract WAV audio from video clip.
          2. Run Faster-Whisper transcription.
          3. Upload audio WAV + pass transcript to Gemini for multimodal cross-referencing.
          4. Save outputs to JSON and TXT.
        """
        if not os.path.exists(video_path):
            raise FileNotFoundError(f"Video file not found: {video_path}")

        clip_dir = os.path.dirname(os.path.abspath(video_path))
        clip_stem = os.path.splitext(os.path.basename(video_path))[0]

        if not output_dir:
            output_dir = os.path.join(clip_dir, "transcription_output")
        os.makedirs(output_dir, exist_ok=True)

        logger.info(f"🚀 Starting ClipTranscriber pipeline for: {os.path.basename(video_path)}")

        # ── Step 1: Extract Audio WAV ──────────────────────────────────────────
        wav_output_path = os.path.join(output_dir, f"{clip_stem}_extracted.wav")
        audio_success = extract_audio(video_path, wav_output_path)

        if not audio_success or not os.path.exists(wav_output_path):
            logger.warning(f"⚠️ Audio extraction failed or clip has no audio stream: {video_path}")
            empty_result = {
                "has_audio": False,
                "accurate_full_transcript": "",
                "semantic_context": {"topic": "Silent Video / No Audio"},
                "llm_system_context_payload": "This clip contains no audio stream or vocal speech."
            }
            self._save_results(output_dir, empty_result, whisper_raw={})
            return empty_result

        # ── Step 2: Faster-Whisper Transcription ──────────────────────────────
        whisper_json_path = os.path.join(output_dir, "whisper_raw.json")
        logger.info(f"🎙️ Running Faster-Whisper ({self.whisper_model_size}) on extracted audio...")
        whisper_data = extract_speech_boundaries(
            audio_wav_path=wav_output_path,
            output_json_path=whisper_json_path,
            model_size=self.whisper_model_size
        )

        # ── Step 3: Gemini Multimodal Audio-Text Cross-Referencing ────────────
        enhanced_result = self._enhance_with_gemini_audio(wav_output_path, whisper_data)

        # ── Step 4: Save & Persist Outputs ─────────────────────────────────────
        final_data = self._save_results(output_dir, enhanced_result, whisper_data)
        logger.info(f"✅ Pipeline complete! Results saved to: {output_dir}")
        return final_data

    def _enhance_with_gemini_audio(
        self,
        audio_wav_path: str,
        whisper_data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Uploads audio WAV file to Gemini and sends raw Faster-Whisper transcript
        for cross-referencing and semantic enrichment.
        """
        if not self.api_key:
            logger.warning("⚠️ GEMINI_API_KEY not found — returning raw Faster-Whisper transcript without Gemini cross-referencing.")
            sentences = [s.get("text", "") for s in whisper_data.get("sentences", [])]
            full_text = " ".join(sentences)
            return {
                "accurate_full_transcript": full_text,
                "whisper_corrections": [],
                "semantic_context": {
                    "topic": "Extracted via Faster-Whisper (Gemini key missing)",
                    "detailed_narrative": full_text,
                    "speaker_intent": "N/A",
                    "emotional_tone": "N/A",
                    "implied_context": "N/A"
                },
                "key_entities_and_facts": {
                    "entities_mentioned": [],
                    "key_takeaways": [s for s in sentences if s]
                },
                "llm_system_context_payload": f"Clip Transcript (Faster-Whisper): {full_text}"
            }

        prompt = GEMINI_CROSS_REF_PROMPT.format(
            whisper_raw_json=json.dumps({
                "sentences": whisper_data.get("sentences", []),
                "duration_sec": whisper_data.get("duration_sec", 0.0),
                "language": whisper_data.get("language", "en")
            }, indent=2)
        )

        try:
            logger.info("🧠 Uploading raw WAV audio to Gemini & initiating multimodal cross-referencing...")
            
            # Attempting via google.genai or google.generativeai
            raw_response_text = None
            
            try:
                from google import genai
                client = genai.Client(api_key=self.api_key)
                uploaded_file = client.files.upload(file=audio_wav_path)
                model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
                response = client.models.generate_content(
                    model=model_name,
                    contents=[uploaded_file, prompt]
                )
                raw_response_text = response.text
            except Exception as e_genai:
                logger.debug(f"genai SDK direct call fallback: {e_genai}")
                try:
                    import google.generativeai as legacy_genai
                    legacy_genai.configure(api_key=self.api_key)
                    uploaded_file = legacy_genai.upload_file(path=audio_wav_path)
                    model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
                    model = legacy_genai.GenerativeModel(model_name)
                    response = model.generate_content([uploaded_file, prompt])
                    raw_response_text = response.text
                except Exception as e_legacy:
                    logger.debug(f"legacy_genai SDK direct call fallback: {e_legacy}")
                    if gemini_router:
                        raw_response_text = gemini_router.generate(
                            prompt=prompt,
                            task_type="creative"
                        )

            if not raw_response_text:
                raise RuntimeError("Failed to obtain response from Gemini API.")

            # Clean JSON formatting
            cleaned_text = raw_response_text.strip()
            if cleaned_text.startswith("```json"):
                cleaned_text = cleaned_text[7:]
            if cleaned_text.startswith("```"):
                cleaned_text = cleaned_text[3:]
            if cleaned_text.endswith("```"):
                cleaned_text = cleaned_text[:-3]
            cleaned_text = cleaned_text.strip()

            parsed_json = json.loads(cleaned_text)
            logger.info("✨ [Gemini Fusion] Audio-Text cross-referencing successfully completed.")
            return parsed_json

        except Exception as err:
            logger.error(f"❌ Gemini audio cross-referencing failed: {err}")
            sentences = [s.get("text", "") for s in whisper_data.get("sentences", [])]
            full_text = " ".join(sentences)
            return {
                "accurate_full_transcript": full_text,
                "whisper_corrections": [],
                "error": str(err),
                "semantic_context": {
                    "topic": "Fallback to Faster-Whisper",
                    "detailed_narrative": full_text
                },
                "llm_system_context_payload": f"Clip Transcript (Whisper Fallback): {full_text}"
            }

    def _save_results(
        self,
        output_dir: str,
        enhanced_result: Dict[str, Any],
        whisper_raw: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Saves results into JSON and TXT format inside the output directory."""
        final_payload = {
            "has_audio": enhanced_result.get("has_audio", True),
            "accurate_full_transcript": enhanced_result.get("accurate_full_transcript", ""),
            "whisper_corrections": enhanced_result.get("whisper_corrections", []),
            "semantic_context": enhanced_result.get("semantic_context", {}),
            "key_entities_and_facts": enhanced_result.get("key_entities_and_facts", {}),
            "llm_system_context_payload": enhanced_result.get("llm_system_context_payload", ""),
            "whisper_raw_data": whisper_raw,
            "processed_at": time.strftime("%Y-%m-%d %H:%M:%S")
        }

        json_out_path = os.path.join(output_dir, "clip_semantic_context.json")
        with open(json_out_path, "w", encoding="utf-8") as f:
            json.dump(final_payload, f, indent=2, ensure_ascii=False)

        txt_out_path = os.path.join(output_dir, "clip_semantic_summary.txt")
        with open(txt_out_path, "w", encoding="utf-8") as f:
            f.write(f"=== CLIP SEMANTIC CONTEXT SUMMARY ===\n\n")
            f.write(f"ACCURATE TRANSCRIPT:\n{final_payload.get('accurate_full_transcript')}\n\n")
            f.write(f"SEMANTIC TOPIC: {final_payload.get('semantic_context', {}).get('topic')}\n")
            f.write(f"EMOTIONAL TONE: {final_payload.get('semantic_context', {}).get('emotional_tone')}\n\n")
            f.write(f"LLM SYSTEM CONTEXT PAYLOAD:\n{final_payload.get('llm_system_context_payload')}\n")

        logger.info(f"📄 Saved context JSON: {json_out_path}")
        logger.info(f"📄 Saved summary TXT: {txt_out_path}")
        return final_payload


def transcribe_and_enhance_clip(video_path: str, model_size: str = "base") -> Dict[str, Any]:
    """Helper shortcut function to run clip transcriber on a video file."""
    transcriber = ClipTranscriber(whisper_model_size=model_size)
    return transcriber.process_clip(video_path)
